name: widget_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  animate_do: ^3.3.4
  flutter_lints: ^3.0.0
  flutter_riverpod: ^2.5.1
  flutter_test:
    sdk: flutter
  go_router: ^13.2.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
